version: 2.0.1-ci{build}

image: Visual Studio 2017

build_script:
  - cmd: build

test_script:
  - cmd: test

artifacts:
  - path: 'src\**\*.nupkg'
  - path: TestResults

deploy:
  - provider: Environment
    name: blob.core.windows.net
    on:
      branch: master
  - provider: Environment
    name: nuget.org
    on:
      branch: release
